[package]
name = "category_assigner"
version = "0.1.0"
authors = ["David Winslow <cdwinslow@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.1"
flate2 = "1.0.13"
rayon = "1.3.0"
rust-stemmers = "1.2.0"
structopt = "0.3.7"
walkdir = "2.2.9"